#!/usr/bin/env bash

#  Rails CI - create_ami - http://github.com/thewoolleyman/railsci
#  Script to automatically create an EC2 EBS boot AMI which will run the official Ruby on Rails Continuous Integration build
#  Copyright (c) 2010 Chad Woolley - The MIT License

create_ami() {
  export AMIBUILDER_CUSTOM_SETUP_URL='http://github.com/thewoolleyman/railsci/raw/master/script/rails_ci_setup'
  wget -O /tmp/amibuilder http://github.com/thewoolleyman/amibuilder/raw/master/amibuilder
  chmod a+x /tmp/amibuilder
  /tmp/amibuilder
}

create_ami
