#!/usr/bin/env bash

#  Rails CI - create_ami - http://github.com/thewoolleyman/railsci
#  Script to automatically create an EC2 EBS boot AMI which will run the standard Ruby on Rails Continuous Integration build
#  Downloads and runs AMIBUILDER - http://github.com/thewoolleyman/amibuilder - which will in turn download and run custom setup script rails_ci_setup.
#  Copyright (c) 2010 Chad Woolley - The MIT License

set -o noclobber
set -e
set -o pipefail
set -o nounset
trap 'echo RAILSCI - create_ami: error on line $LINENO' ERR


create_ami() {
  railsci_config=${RAILSCI_CONFIG:-~/.railscirc}
  if [ -e $railsci_config ]; then
    source $railsci_config
  fi
  
  AMIBUILDER_URL=${AMIBUILDER_URL:-'http://github.com/thewoolleyman/amibuilder/raw/master/amibuilder'}
  AMIBUILDER_CUSTOM_SETUP_URL=${AMIBUILDER_CUSTOM_SETUP_URL:-'http://github.com/thewoolleyman/railsci/raw/master/script/rails_ci_setup'}
  
  AMIBUILDER_CUSTOM_SETUP_VARS=${AMIBUILDER_CUSTOM_SETUP_VARS:-''}
  RAILSCI_AMIBUILDER_VARS=${RAILSCI_AMIBUILDER_VARS:-''}
  wget -O /tmp/amibuilder $AMIBUILDER_URL
  chmod a+x /tmp/amibuilder
  eval "$RAILSCI_AMIBUILDER_VARS /tmp/amibuilder"
}

create_ami
