#!/usr/bin/env bash

#  Rails CI - railsci_build_ami - http://github.com/thewoolleyman/railsci
#  Script to automatically create an EC2 EBS boot AMI which will run the standard Ruby on Rails Continuous Integration build
#  Downloads and runs boxbuilder - http://github.com/thewoolleyman/boxbuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

# TODO: finish