#!/usr/bin/env bash

#  Rails CI - rails_ci_setup - http://github.com/thewoolleyman/railsci
#  Script to automatically configure an EC2 EBS boot AMI which will run the standard Ruby on Rails Continuous Integration build.
#  Intended to be automatically downloaded and called as a custom setup script from AMIBUILDER - http://github.com/thewoolleyman/amibuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

set -o noclobber
set -e
set -o pipefail
set -o nounset
trap 'echo RAILSCI - create_ami: error on line $LINENO' ERR

config() {
  RAILSCI_RVM_RUBIES=${RAILSCI_RVM_RUBIES:-'1.8.7-p174 1.9.2'}
  RAILSCI_RVM_DEFAULT_RUBY=${RAILSCI_RVM_DEFAULT_RUBY:-'1.8.7-p174'}
  RAILSCI_NO_INSTALL_PACKAGES=${RAILSCI_NO_INSTALL_PACKAGES:-false}
  RAILSCI_NO_SETUP_RVM=${RAILSCI_NO_SETUP_RVM:-false}
  RAILSCI_NO_SETUP_CHEF=${RAILSCI_NO_SETUP_CHEF:-false}
}

install_packages() {
  echo "RAILSCI: Updating Aptitude..."
  sudo apt-get update
  echo "RAILSCI: Installing packages to build Ruby..."
  sudo apt-get install -y build-essential zlib1g zlib1g-dev libssl-dev openssl libreadline5-dev openssh-server openssh-client ssh wget
  echo "RAILSCI: Installing packages recommended by RVM..."
  sudo apt-get install -y bison libxml2-dev git-core
}

install_rvm() {
  echo "RAILSCI: Installing RVM..."
  curl -O http://rvm.beginrescueend.com/releases/rvm-install-latest
  chmod a+x rvm-install-latest
  ./rvm-install-latest
}

enable_rvm() {
  echo "RAILSCI: Enabling RVM in init file $init_file"
  rvm_init="if [[ -s $HOME/.rvm/scripts/rvm ]] ; then source $HOME/.rvm/scripts/rvm ; fi"
  if rvm_line=$(grep '.rvm' $init_file); test -z "$rvm_line"; then
    echo $rvm_init >> $init_file
  fi
  # mount proc to avoid error message from sed: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=559539
  # sudo mount -t proc none /proc/  # comment for now, fails if proc already mounted
  sed -i'.bak' -e 's/^.*&& return.*$//' $init_file
  source $init_file
}

install_rvm_rubies() {
  for rvm_ruby in $RAILSCI_RVM_RUBIES
  do
    echo "RAILSCI: Installing RVM ruby: $rvm_ruby"
    rvm install $rvm_ruby
  done
}

set_rvm_default_ruby() {
  rvm --default use $RAILSCI_RVM_DEFAULT_RUBY
}

setup_rvm() {
  echo "RAILSCI: Setting up RVM..."
  install_rvm
  for init_file in ~/.bashrc ~/.bash_profile
  do
    if [[ -e $init_file ]]; then
      enable_rvm
    fi
  done
  install_rvm_rubies
  set_rvm_default_ruby
}

setup_chef() {
  echo "RAILSCI: Setting up Chef..."
  gem install chef
}

setup_all() {
  echo "RAILSCI: Setting up Rails CI..."
  if [[ ! $RAILSCI_NO_INSTALL_PACKAGES = true ]] ; then
    install_packages
  fi
  if [[ ! $RAILSCI_NO_SETUP_RVM = true ]] ; then
    setup_rvm
  fi
  if [[ ! $RAILSCI_NO_SETUP_CHEF = true ]] ; then
    setup_chef
  fi
}

config
setup_all
